### ISSUE TITLE
Does not respond when run in Docker Container

### ISSUE THREAD

**Issue by timblackwell** [mozilla-services/aws-signing-proxy#2]
Steps to reproduce

1. `docker run -d -p 8000:8000 mozilla/aws-signing-proxy:latest`
1. `curl localhost:8000`

There is no errors or access logs in the container logs.

If running on host machine `go run main.go`,`curl localhost:8000` will show access log `2018/03/20 17:13:36 GET /`

How do you run the docker image and have it respond?

**Comment by milescrabill** [comment]
Do you see any output from `curl`? When I run `docker run -p 8000:8000 mozilla/aws-signing-proxy:latest` and `curl localhost:8000` I get `curl: (52) Empty reply from server`. This is equivalent to the client never being able to talk HTTP to the server, or at least never getting any response.

Importantly, if I `docker run -p 8000:8000 -p 8001:8001 mozilla/aws-signing-proxy:latest` (nothing listening on 8001, but forwarding it), I also get `curl: (52) Empty reply from server` when I `curl localhost:8001`. My impression is that this is an artifact of how docker port forwarding works (on macOS?)`[1]` - we can open a connection on the port, put there's nothing to connect to.

The process is running inside the container, and the port is forwarded, but the server is only configured to accept connections on `localhost`, i.e. from the container. This is because by default `aws-signing-proxy` listens on `localhost`, per the configuration block.

If I run `docker run -p 8000:8000 -e SIGNING_PROXY_LISTEN="0.0.0.0:8000" mozilla/aws-signing-proxy:latest`, and `curl localhost:8000`, logs properly show up from the container. You'll probably have to configure `SIGNING_PROXY_DESTINATION` and `SIGNING_PROXY_REGION` for anything useful to happen beyond that.

Listening on `localhost` _sort of_ violates the principle of least surprise - if you run a webserver, you generally want it to be accessible beyond `localhost`. I configured `localhost` as the default because my primary use case has the proxy listening on `localhost` with `--net=host` configured for the container, so it's accessible from the host on `localhost`.

`[1] `port forwarding and `--net=host` are a little subtle on macOS, because docker for mac runs a linux vm under the hood - so `--net=host` will only work as I described in docker on linux.

**Comment by milescrabill** [comment]
Given that running in a docker container is absolutely expected for this service, and not everyone runs with `--net=host`, I'm going to change the default to listen on `0.0.0.0` and add a soft warning to the readme about it.

Thanks for your feedback! It gave me a chance to dig into some of the docker guts behind this.

**Comment by milescrabill** [comment]
I've made the change I mentioned in https://github.com/mozilla-services/aws-signing-proxy/commit/4d0847a9381af055e039ee990000b5ed580b595f, which I've released as 1.0.3. Hopefully your problem was actually caused by what I thought it was, ha!

**Comment by timblackwell** [comment]
Ah that makes sense. It had been a long day and just presumed localhost:8000 would work the same in the container as my host.

Thanks for the quick detailed reply and fix!
